fix: use pagination to fetch all queries
neutron-org/neutron-query-relayer pull request #57
Opened 2022-11-03 10:11 UTC by swelf19

Tested manually.

2022-11-06 11:49 UTC, oopcode approved these changes
tested, works fine

2022-11-06 12:17 UTC, foxpy commented on internal/subscriber/utils.go
>  	// TODO: use pagination.
This TODO definitely doesn't make any sense at this point :)

2022-11-07 07:50 UTC, foxpy requested changes
Please fix my comment about TODO and I am ready to approve it.

2022-11-07 08:18 UTC, oopcode approved these changes

2022-11-07 09:08 UTC, merged