chore: NTRN-268. Refactor trusted header fetcher interface in ICQ relayer
neutron-org/neutron-query-relayer pull request #69
Opened 2022-12-12 13:50 UTC by albertandrejev

**Summary**

[Here](https://github.com/neutron-org/neutron-query-relayer/blob/main/internal/relay/trusted_headers.go) we have two almost similar functions defined. Since it is very confusing, it should be refactored.

**DoD**
- [x] FetchTrustedHeaderForHeight is used for KV query submission. It should be renamed into Fetch.
- [x] FetchTrustedHeadersForHeights is used for TX query submission. It should be deleted from trusted header fetcher interface and rewritten as helper function inside TX submission module.

Closes https://p2pvalidator.atlassian.net/browse/NTRN-268

Test run: https://github.com/neutron-org/neutron-tests/actions/runs/3947735784

2022-12-16 08:29 UTC, foxpy approved these changes

2022-12-20 19:17 UTC, pr0n00gler requested changes

2022-12-20 19:17 UTC, pr0n00gler commented on internal/txprocessor/txprocessor.go
> +// `height` - remote chain block height X = transaction with such block height
Comment about arguments is copy pasted from the removed `FetchTrustedHeadersForHeights` method and wrong for the `prepareHeaders` method

2022-12-20 19:53 UTC, pr0n00gler approved these changes

2022-12-24 15:37 UTC, foxpy approved these changes

2023-01-10 14:33 UTC, oopcode approved these changes

2023-01-17 12:31 UTC, swelf19 approved these changes

2023-01-17 12:34 UTC, ratik approved these changes

2023-01-18 11:27 UTC, merged