Chore: bump deps
neutron-org/neutron-query-relayer pull request #75
Opened 2023-02-02 14:25 UTC by pr0n00gler

2023-02-02 15:10 UTC, quasisamurai approved these changes

2023-02-02 15:10 UTC, swelf19 approved these changes

2023-02-02 15:13 UTC, foxpy requested changes
Have you tried running `go mod tidy` on this branch? It fails for me with error messages like this:
```
github.com/neutron-org/neutron-query-relayer/internal/kvprocessor imports
        github.com/cosmos/relayer/v2/relayer/chains/cosmos imports
        github.com/strangelove-ventures/lens/client: github.com/strangelove-ventures/lens@v0.5.2-0.20220725181212-615bf7a39fe6: invalid version: unknown revision 615bf7a39fe6
```

2023-02-02 15:16 UTC, pr0n00gler commented
> Have you tried running `go mod tidy` on this branch? It fails for me with error messages like this:
> 
> ```
> github.com/neutron-org/neutron-query-relayer/internal/kvprocessor imports
>         github.com/cosmos/relayer/v2/relayer/chains/cosmos imports
>         github.com/strangelove-ventures/lens/client: github.com/strangelove-ventures/lens@v0.5.2-0.20220725181212-615bf7a39fe6: invalid version: unknown revision 615bf7a39fe6
> ```

Yes I have, everything works

2023-02-02 15:27 UTC, foxpy commented
> Yes I have, everything works

Turns out I had to upgrade from go 1.18 to go 1.20

2023-02-02 15:27 UTC, foxpy approved these changes

2023-02-03 08:26 UTC, sotnikov-s approved these changes

2023-02-03 08:58 UTC, merged