fix: bug when relayer fails if query id is not removed #ntrn-182
neutron-org/neutron-query-relayer pull request #86
Opened 2024-03-11 12:19 UTC by NeverHappened

https://hadronlabs.atlassian.net/browse/NTRN-182

When query id is removed from the neutron, but not yet synced with relayer, it can return error when searching for it.
Before it completely failed the relayer, now we just continue since it does not break anything

2024-03-19 12:09 UTC, NeverHappened commented
https://github.com/neutron-org/neutron-tests/actions/runs/8340887685

2024-04-08 16:02 UTC, pr0n00gler approved these changes

2024-04-09 12:43 UTC, joldie777 requested changes

2024-04-10 10:39 UTC, joldie777 approved these changes

2024-04-10 11:14 UTC, pr0n00gler approved these changes

2024-04-12 08:27 UTC, merged