Feat/dynamic fees
neutron-org/neutron-query-relayer pull request #91
Opened 2024-06-11 20:36 UTC by quasisamurai

2024-06-18 10:13 UTC, pr0n00gler requested changes

2024-06-18 10:13 UTC, pr0n00gler commented on internal/submit/tx_sender.go
> +	gasPrice, err := txs.getGasPrice(ctx)
I don't quite understand, you are saying:
> If query fails for some reason -> relayer uses default gp from config

But the logic does the exact opposite - it does return an error that query failed and does not uses default gas prices.

2024-06-18 17:19 UTC, quasisamurai commented on internal/submit/tx_sender.go
> +	gasPrice, err := txs.getGasPrice(ctx)
this logic implemented inside `getGasPrice` func
<img width="567" alt="Снимок экрана 2024-06-18 в 14 18 49" src="https://github.com/neutron-org/neutron-query-relayer/assets/26491894/78660189-4acd-4772-b5a8-bbb77ef1c370">

2024-06-20 11:45 UTC, quasisamurai commented
https://github.com/neutron-org/neutron-tests/actions/runs/9582405898/job/26428850191

2024-06-21 10:18 UTC, joldie777 commented on internal/submit/tx_sender.go
> +	if err != nil {
Why do we need err check here?

2024-06-24 14:28 UTC, swelf19 reviewed
Let's set default gas price with a really low value in integration tests to  see if dynamic prices really works

2024-06-24 14:28 UTC, swelf19 commented on internal/submit/tx_sender.go
> +	getPricesQueryPath           = "/feemarket.feemarket.v1.Quuery/GasPrice"
looks like an error, does dynamic prices work at all?
```suggestion
	getPricesQueryPath           = "/feemarket.feemarket.v1.Query/GasPrice"
```

2024-06-24 14:28 UTC, swelf19 commented on internal/submit/tx_sender.go
> +	if err != nil {
lets log the error here

2024-06-24 14:28 UTC, swelf19 commented on internal/submit/tx_sender.go
> +	simQuery := abci.RequestQuery{
actually you do not use the structure, we can get rid of it

2024-06-24 16:48 UTC, joldie777 submitted a review, later dismissed

2024-06-28 11:33 UTC, swelf19 approved these changes

2024-07-01 13:30 UTC, pr0n00gler commented
Please, resolve conflicts

2024-07-02 14:11 UTC, pr0n00gler approved these changes

2024-07-03 09:56 UTC, joldie777 approved these changes

2024-07-05 15:11 UTC, quasisamurai commented
https://github.com/neutron-org/neutron-tests/actions/runs/9798300917

2024-07-06 10:39 UTC, merged